version: "3.3"
services:
  db:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo16:
    image: odoo:16.0
    user: root
    depends_on:
      - db
    ports:
      - "8000:8069"
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      # - ./entrypoint.sh:/entrypoint.sh
      - ./custom-addons:/mnt/custom-addons
      - ./etc:/etc/odoo
    restart: always















# version: "3.3"
# services:
#   odoo:
#     image: odoo:16.0 #image of odoo
#     env_file: .env #environment file
#     depends_on:
#       - postgres
#     ports:
#       - "8000:8069" # port mapping
#     volumes: #mapping directory
#       - data:/var/lib/odoo
#       - ./config:/etc/odoo
#       - ./extra-addons:/mnt/extra-addons
#   postgres:
#     image: postgres:13 #postgres image
#     env_file: .env #environment file(contains postgres environment)
#     volumes:
#       - db:/var/lib/postgresql/data/pgdata
#     expose:
#       - "5432"
# volumes:
#   data:
#   db:

